### ISSUE TITLE
Binary store fails.

### ISSUE THREAD

**Issue by gettes** [mfenniak/dynamodb_fdw#22] opened 2024-05-21 14:25 UTC
Hi @mfenniak - it's not working.  I am getting 
```
"SQL Error [XX000]: ERROR: Error in python: TypeError
  Detail: Input string must be text, not bytes"
```

I have created in PG:
```
CREATE FOREIGN TABLE public.ddb_img1 (
	"oid" text NULL,
	pkey text OPTIONS(mapped_attr 'pkey', partition_key 'true') NULL,
	img BYTEA OPTIONS (mapped_attr 'img'),
	"document" json OPTIONS(ddb_document 'true') NULL
);
```
In DDB I have confirmed the field img is binary (i also tried without this field and got the same result).
I have copied a binary image into a table on PG and then I use:
```
insert into ddb_img1 (pkey, img)
	select id, image  from public.img1;
```
and this generates the error above.
When I build I am pulling from main branch.
I am sure I am doing something wrong but I am not sure what.
Thank you so much!

**Comment by mfenniak** [comment] 2024-05-21 16:37
@gettes I've been able to reproduce this.  Looks like there's a bug when inserting without the `document` field -- the code requires it to be present even if it is marked as null and not being used.  As a workaround you can do:
```sql
insert into ddb_img1 (pkey, img, document)
    select id, image, '{}' from public.img1;
```
I should be able to fix the issue shortly as well.

**Closed as completed** 2024-05-21 16:48 UTC

**Comment by gettes** [comment] 2024-05-21 16:56
Yup - all fixed now.  I will continue my testing.  THANK YOU SO MUCH!
